version: '3'
services:
  app:
    image: badconfig/gton_api_server 
    container_name: app_api_server
    tty: true
    ports:
      - "8088:8088"
    env_file:
      - ./gton_api_server/.env
    environment:
      - DATABASE_URL=postgres://docker:sdfjksfu2jkl45g343b@postgres1:5432/diesel_db
      - RUST_BACKTRACE=1
    volumes:
      - ./gton_api_server/migrations:/gton_api_server/migrations
    networks:
      - app-network
  # poller:
  #   image: badconfig/ftm_poller
  #   container_name: poller
  #   tty: true
  #   environment:
  #     - DATABASE_URL=postgres://docker:sdfjksfu2jkl45g343b@postgres1:5432/diesel_db
  #   networks:
  #     - app-network
  postgres:
    image: "postgres:12.6"
    container_name: postgres1
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: diesel_db
      POSTGRES_PASSWORD: sdfjksfu2jkl45g343b
      POSTGRES_USER: docker
    networks:
      - app-network
    volumes:
      - pg_redrufus:/var/lib/postgresql/data
volumes:
  pg_redrufus:
networks:
  app-network:
    driver: bridge
